name: Run Python Scripts and Update Encrypted Database

on:
  schedule:
    - cron: "*/30 * * * *"  
  workflow_dispatch:  
jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.3

    - name: Decrypt sent_articles.db
      run: |
        gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.GPG_PASSPHRASE }}" \
        --output sent_articles.db sent_articles.db.gpg

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Securityboulevard script
      run: python Securityboulevard.py
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    - name: Run csoonline script
      run: python csoonline.py
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    - name: Run helpnetsecurity script
      run: python helpnetsecurity.py
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    - name: Run thehackernews script
      run: python thehackernews.py
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    - name: Re-encrypt sent_articles.db
      run: |
        gpg --symmetric --cipher-algo AES256 --batch --yes --passphrase "${{ secrets.GPG_PASSPHRASE }}" \
        --output sent_articles.db.gpg sent_articles.db

    - name: Commit changes
      run: |
        git config --global user.email "${{ secrets.USER_EMAIL }}"  # Use your GitHub email (stored as secret)
        git config --global user.name "GitHub Action"
        git add sent_articles.db.gpg
        git commit -m "Update encrypted sent_articles.db" || echo "No changes to commit"
      continue-on-error: true  

    - name: Push changes
      run: git push origin main
      continue-on-error: true  
