name: Run Python Scripts and Update Encrypted Database

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}  # Changed to PAT
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Configure Git
        run: |
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global user.name "GitHub Actions Bot"
          # Set remote URL with PAT for authentication
          git remote set-url origin https://${{ github.actor }}:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Pull latest changes
        run: git pull origin main --rebase

      - name: Decrypt database
        run: |
          if [ -f sent_articles.db.gpg ]; then
            gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.GPG_PASSPHRASE }}" \
            --output sent_articles.db sent_articles.db.gpg
          else
            echo "No encrypted database found, creating new empty database."
            touch sent_articles.db
          fi

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run helpnetsecurity script
        run: python helpnetsecurity.py

      - name: Run thehackernews script
        run: python thehackernews.py
        
      - name: Run bleepingcomputer script
        run: python bleepingcomputer.py

      - name: Re-encrypt database
        run: |
          gpg --symmetric --cipher-algo AES256 --batch --yes --passphrase "${{ secrets.GPG_PASSPHRASE }}" \
          --output sent_articles.db.gpg sent_articles.db

      - name: Commit and push changes
        run: |
          git add sent_articles.db.gpg
          if ! git diff --cached --quiet; then
            git commit -m "Update encrypted sent_articles.db [skip ci]"
            git pull --rebase origin main
            git push origin main
          else
            echo "No changes to commit"
          fi
